import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Lang = 'ru' | 'kz' | 'en';

interface LangStore {
  lang: Lang;
  setLang: (l: Lang) => void;
}

export const useLangStore = create<LangStore>()(
  persist(
    (set) => ({
      lang: 'ru',
      setLang: (lang) => set({ lang }),
    }),
    { name: 'aqbobek-lang' }
  )
);

export const translations: Record<Lang, Record<string, string>> = {
  ru: {
    // sidebar
    home: 'Главная', grades: 'Оценки', performance: 'Успеваемость',
    schedule: 'Расписание', materials: 'Материалы', analytics: 'Аналитика',
    wellness: 'Тесты', canteen: 'Буфет', achievements: 'Достижения',
    news: 'Новости', reports: 'Отчёты', nisgram: 'Лента',
    study: 'Учёба', school_life: 'Школьная жизнь', edu_process: 'Учебный процесс',
    my_children: 'Мои дети', management: 'Управление',
    role_student: 'Ученик', role_teacher: 'Учитель', role_admin: 'Администратор',
    role_parent: 'Родитель', role_kiosk: 'Стенд', logout: 'Выйти',
    // student dashboard
    hello: 'Привет', your_dashboard: 'Твой учебный дашборд',
    avg_grade: 'Средний балл', best_subject: 'Лучший предмет',
    needs_work: 'Нужно подтянуть', radar: 'Радар успеваемости',
    grades_by_subject: 'Оценки по предметам', pay_attention: 'Обрати внимание',
    avg_below: 'Средний балл ниже 3.5 по', check_performance: 'Загляни в раздел «Успеваемость»',
    excellent: 'Отличник', good: 'Хорошист', ok: 'Справляется', help: 'Нужна помощь',
    growing: 'растут', falling: 'падают', stable: 'Стабильно',
    // grades page
    my_grades: 'Мои оценки', avg_by_subject: 'Средний балл по предметам',
    last_grades: 'Последние оценки', subject: 'Предмет', type: 'Тип',
    topic: 'Тема', date: 'Дата', grade: 'Оценка',
    all: 'Все', q1: '1 четв.', q2: '2 четв.', q3: '3 четв.', q4: '4 четв.',
    // ai tutor
    performance_by_subject: 'Успеваемость по предметам',
    avg_grades_dynamics: 'Средние баллы, динамика и зоны роста',
    focus_on: 'Уделить больше внимания', compare_subjects: 'Сравнение по предметам',
    grade_excellent: 'Отлично', grade_good: 'Хорошо', grade_ok: 'Удовлетворительно',
    grade_bad: 'Нужно поработать', n_grades: 'оценок', rising: 'растёт',
    declining: 'снижается',
    // teacher dashboard
    good_day: 'Добрый день', lessons_per_week: 'уроков в неделю',
    lessons_today: 'Уроки сегодня', no_lessons: 'Сегодня уроков нет',
    grade_students: 'Выставить оценки ученикам по классу',
    upload_materials: 'Загрузить учебные материалы и ДЗ',
    class_analytics: 'Аналитика класса',
    student_performance: 'Успеваемость учеников', open: 'Открыть',
    announcements: 'Объявления и новости',
    // kundelik
    day_progress: 'Прогресс учебного дня', lessons: 'уроков',
    passed: 'прошло', current_lesson: 'Сейчас идёт', next_lesson: 'Следующий урок',
    no_lessons_today: 'Уроков сегодня нет', today_schedule: 'Расписание на сегодня',
    homework: 'Домашние задания', sync: 'Синхронизировать', cancelled: 'Отменён',
    // nisgram
    achievements_feed: 'Лента',
    feed_subtitle: 'Успехи и достижения учеников лицея',
    new_achievement: 'Новое достижение', mentor: 'Наставник',
    pending_moderation: 'Ожидают модерации', no_posts: 'Пока нет публикаций',
    add_achievement: '+ Добавить достижение', title_placeholder: 'Заголовок',
    description_placeholder: 'Описание...', submit_moderation: 'Отправить на модерацию',
    approve: 'Принять', reject: 'Отклонить',
    // wellness
    tests_and_psychologist: 'Тесты и психолог',
    wellness_subtitle: 'Узнайте о себе больше · Результаты видите только вы',
    book_psychologist: 'Запись к психологу',
    booking_subtitle: 'Конфиденциально · Бесплатно · Без осуждения',
    specialist: 'Специалист', day: 'День', time: 'Время', room: 'Кабинет',
    reason: 'Причина', booking_done: 'Запись оформлена',
    take_test: 'Пройти тест', collapse: 'Свернуть', retake: 'Пройти снова',
    view_result: 'Посмотреть результат', book: 'Записаться', back: 'Назад',
    next: 'Продолжить', change: 'Изменить',
    reason_placeholder: 'Причина обращения (необязательно)',
    // currency
    school_canteen: 'Школьный буфет', coin_rate: '1 монета = 1 тенге',
    coins: 'монет', order_done: 'Заказ оформлен!', qr_for_cashier: 'QR-код для кассы',
    show_cashier: 'Покажи на кассе', tx_history: 'История транзакций',
    menu_tab: 'Меню', my_orders: 'Мои заказы', order_btn: 'Заказать',
    close: 'Закрыть', received: 'Получен', pending: 'Ожидает', no_orders: 'Заказов пока нет',
    // gamification
    points: 'баллов', points_history: 'История начислений', lyceum_rating: 'Рейтинг лицея',
    add_item: 'Добавить достижение', tab_points: 'Баллы', tab_leaderboard: 'Лидерборд',
    tab_shop: 'Магазин', tab_portfolio: 'Портфолио', buy: 'Купить', add: '+ Добавить',
    verified: 'Верифицировано', name_placeholder: 'Название',
  },
  kz: {
    home: 'Басты бет', grades: 'Бағалар', performance: 'Үлгерім',
    schedule: 'Кесте', materials: 'Материалдар', analytics: 'Аналитика',
    wellness: 'Тесттер', canteen: 'Буфет', achievements: 'Жетістіктер',
    news: 'Жаңалықтар', reports: 'Есептер', nisgram: 'Лента',
    study: 'Оқу', school_life: 'Мектеп өмірі', edu_process: 'Оқу процесі',
    my_children: 'Менің балаларым', management: 'Басқару',
    role_student: 'Оқушы', role_teacher: 'Мұғалім', role_admin: 'Әкімші',
    role_parent: 'Ата-ана', role_kiosk: 'Стенд', logout: 'Шығу',
    hello: 'Сәлем', your_dashboard: 'Оқу тақтасы',
    avg_grade: 'Орташа баға', best_subject: 'Үздік пән',
    needs_work: 'Жақсарту керек', radar: 'Үлгерім радары',
    grades_by_subject: 'Пәндер бойынша бағалар', pay_attention: 'Назар аудар',
    avg_below: 'Орташа баға 3.5 төмен', check_performance: '«Үлгерім» бөліміне кіріңіз',
    excellent: 'Үздік', good: 'Жақсы', ok: 'Қанағаттанарлық', help: 'Көмек керек',
    growing: 'өсуде', falling: 'төмендеуде', stable: 'Тұрақты',
    my_grades: 'Менің бағаларым', avg_by_subject: 'Пәндер бойынша орташа баға',
    last_grades: 'Соңғы бағалар', subject: 'Пән', type: 'Түрі',
    topic: 'Тақырып', date: 'Күні', grade: 'Баға',
    all: 'Барлығы', q1: '1 тоқсан', q2: '2 тоқсан', q3: '3 тоқсан', q4: '4 тоқсан',
    performance_by_subject: 'Пәндер бойынша үлгерім',
    avg_grades_dynamics: 'Орташа бағалар, динамика және өсу аймақтары',
    focus_on: 'Көбірек назар аудару керек', compare_subjects: 'Пәндерді салыстыру',
    grade_excellent: 'Өте жақсы', grade_good: 'Жақсы', grade_ok: 'Қанағаттанарлық',
    grade_bad: 'Жұмыс істеу керек', n_grades: 'баға', rising: 'өсуде',
    declining: 'төмендеуде',
    good_day: 'Қайырлы күн', lessons_per_week: 'сабақ/апта',
    lessons_today: 'Бүгінгі сабақтар', no_lessons: 'Бүгін сабақ жоқ',
    grade_students: 'Сынып оқушыларына баға қою',
    upload_materials: 'Оқу материалдарын жүктеу',
    class_analytics: 'Сынып аналитикасы',
    student_performance: 'Оқушылардың үлгерімі', open: 'Ашу',
    announcements: 'Хабарландырулар мен жаңалықтар',
    day_progress: 'Оқу күнінің барысы', lessons: 'сабақ',
    passed: 'өтті', current_lesson: 'Қазір жүріп жатыр', next_lesson: 'Келесі сабақ',
    no_lessons_today: 'Бүгін сабақ жоқ', today_schedule: 'Бүгінгі кесте',
    homework: 'Үй тапсырмасы', sync: 'Синхрондау', cancelled: 'Болдырылмады',
    achievements_feed: 'Лента',
    feed_subtitle: 'Лицей оқушыларының жетістіктері',
    new_achievement: 'Жаңа жетістік', mentor: 'Тәлімгер',
    pending_moderation: 'Модерация күтуде', no_posts: 'Әзірше жарияланым жоқ',
    add_achievement: '+ Жетістік қосу', title_placeholder: 'Тақырып',
    description_placeholder: 'Сипаттама...', submit_moderation: 'Модерацияға жіберу',
    approve: 'Қабылдау', reject: 'Қабылдамау',
    tests_and_psychologist: 'Тесттер және психолог',
    wellness_subtitle: 'Өзіңіз туралы көбірек біліңіз · Нәтижелерді тек сіз көресіз',
    book_psychologist: 'Психологқа жазылу',
    booking_subtitle: 'Құпия · Тегін · Сынсыз',
    specialist: 'Маман', day: 'Күн', time: 'Уақыт', room: 'Кабинет',
    reason: 'Себеп', booking_done: 'Жазылым рәсімделді',
    take_test: 'Тест тапсыру', collapse: 'Жию', retake: 'Қайта тапсыру',
    view_result: 'Нәтижені көру', book: 'Жазылу', back: 'Артқа',
    next: 'Жалғастыру', change: 'Өзгерту',
    reason_placeholder: 'Өтініш себебі (міндетті емес)',
    school_canteen: 'Мектеп буфеті', coin_rate: '1 монета = 1 теңге',
    coins: 'монета', order_done: 'Тапсырыс рәсімделді!', qr_for_cashier: 'Касса үшін QR-код',
    show_cashier: 'Кассирге көрсет', tx_history: 'Транзакция тарихы',
    menu_tab: 'Мәзір', my_orders: 'Менің тапсырыстарым', order_btn: 'Тапсырыс беру',
    close: 'Жабу', received: 'Алынды', pending: 'Күтуде', no_orders: 'Тапсырыс жоқ',
    points: 'ұпай', points_history: 'Есептеу тарихы', lyceum_rating: 'Лицей рейтингі',
    add_item: 'Жетістік қосу', tab_points: 'Ұпайлар', tab_leaderboard: 'Рейтинг',
    tab_shop: 'Дүкен', tab_portfolio: 'Портфолио', buy: 'Сатып алу', add: '+ Қосу',
    verified: 'Расталған', name_placeholder: 'Атауы',
  },
  en: {
    home: 'Home', grades: 'Grades', performance: 'Performance',
    schedule: 'Schedule', materials: 'Materials', analytics: 'Analytics',
    wellness: 'Wellness', canteen: 'Canteen', achievements: 'Achievements',
    news: 'News', reports: 'Reports', nisgram: 'Feed',
    study: 'Studies', school_life: 'School Life', edu_process: 'Teaching',
    my_children: 'My Children', management: 'Management',
    role_student: 'Student', role_teacher: 'Teacher', role_admin: 'Administrator',
    role_parent: 'Parent', role_kiosk: 'Kiosk', logout: 'Log out',
    hello: 'Hello', your_dashboard: 'Your learning dashboard',
    avg_grade: 'Average grade', best_subject: 'Best subject',
    needs_work: 'Needs improvement', radar: 'Performance radar',
    grades_by_subject: 'Grades by subject', pay_attention: 'Pay attention',
    avg_below: 'Average below 3.5 in', check_performance: 'Check the Performance section',
    excellent: 'Excellent', good: 'Good', ok: 'Satisfactory', help: 'Needs help',
    growing: 'growing', falling: 'falling', stable: 'Stable',
    my_grades: 'My Grades', avg_by_subject: 'Average by subject',
    last_grades: 'Recent grades', subject: 'Subject', type: 'Type',
    topic: 'Topic', date: 'Date', grade: 'Grade',
    all: 'All', q1: 'Q1', q2: 'Q2', q3: 'Q3', q4: 'Q4',
    performance_by_subject: 'Performance by subject',
    avg_grades_dynamics: 'Average grades, dynamics and growth zones',
    focus_on: 'Focus more on', compare_subjects: 'Subject comparison',
    grade_excellent: 'Excellent', grade_good: 'Good', grade_ok: 'Satisfactory',
    grade_bad: 'Needs work', n_grades: 'grades', rising: 'rising',
    declining: 'declining',
    good_day: 'Good day', lessons_per_week: 'lessons/week',
    lessons_today: 'Today\'s lessons', no_lessons: 'No lessons today',
    grade_students: 'Grade students by class',
    upload_materials: 'Upload study materials & homework',
    class_analytics: 'Class analytics',
    student_performance: 'Student performance', open: 'Open',
    announcements: 'Announcements & news',
    day_progress: 'School day progress', lessons: 'lessons',
    passed: 'done', current_lesson: 'Now in progress', next_lesson: 'Next lesson',
    no_lessons_today: 'No lessons today', today_schedule: 'Today\'s schedule',
    homework: 'Homework', sync: 'Sync', cancelled: 'Cancelled',
    achievements_feed: 'Feed',
    feed_subtitle: 'Student achievements at Aqbobek Lyceum',
    new_achievement: 'New achievement', mentor: 'Mentor',
    pending_moderation: 'Pending moderation', no_posts: 'No posts yet',
    add_achievement: '+ Add achievement', title_placeholder: 'Title',
    description_placeholder: 'Description...', submit_moderation: 'Submit for review',
    approve: 'Approve', reject: 'Reject',
    tests_and_psychologist: 'Wellness & Psychologist',
    wellness_subtitle: 'Learn more about yourself · Only you see results',
    book_psychologist: 'Book a psychologist',
    booking_subtitle: 'Confidential · Free · Non-judgmental',
    specialist: 'Specialist', day: 'Day', time: 'Time', room: 'Room',
    reason: 'Reason', booking_done: 'Appointment booked',
    take_test: 'Take test', collapse: 'Collapse', retake: 'Retake',
    view_result: 'View result', book: 'Book', back: 'Back',
    next: 'Continue', change: 'Change',
    reason_placeholder: 'Reason for visit (optional)',
    school_canteen: 'School Canteen', coin_rate: '1 coin = 1 tenge',
    coins: 'coins', order_done: 'Order placed!', qr_for_cashier: 'QR code for cashier',
    show_cashier: 'Show at cashier', tx_history: 'Transaction history',
    menu_tab: 'Menu', my_orders: 'My Orders', order_btn: 'Order',
    close: 'Close', received: 'Received', pending: 'Pending', no_orders: 'No orders yet',
    points: 'points', points_history: 'Points history', lyceum_rating: 'Lyceum rating',
    add_item: 'Add achievement', tab_points: 'Points', tab_leaderboard: 'Leaderboard',
    tab_shop: 'Shop', tab_portfolio: 'Portfolio', buy: 'Buy', add: '+ Add',
    verified: 'Verified', name_placeholder: 'Name',
  },
};

export function useT() {
  const lang = useLangStore((s) => s.lang);
  return (key: string): string => translations[lang]?.[key] ?? key;
}
